# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Research/FPGA-RE/XilinxExample/XilinxExample.srcs/sources_1/ip/test_rom/test_rom.xci
# IP: The module: 'test_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Research/FPGA-RE/XilinxExample/XilinxExample.gen/sources_1/ip/test_rom/test_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Research/FPGA-RE/XilinxExample/XilinxExample.srcs/sources_1/ip/test_rom/test_rom.xci
# IP: The module: 'test_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Research/FPGA-RE/XilinxExample/XilinxExample.gen/sources_1/ip/test_rom/test_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
